#!/bin/bash

# Railway Environment Variables Injection Script
# This script ensures environment variables are available at runtime

echo "🔧 Railway Environment Variables Setup"

# Create a runtime environment file
cat > /app/.env.local << EOF
NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
EOF

# Create a JavaScript file with environment variables
cat > /app/public/env.js << 'EOF'
window.__ENV = {
  NEXT_PUBLIC_FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL
};
EOF

# Replace placeholders in env.js with actual values
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_API_KEY/'${NEXT_PUBLIC_FIREBASE_API_KEY}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/'${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID/'${NEXT_PUBLIC_FIREBASE_PROJECT_ID}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/'${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/'${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_APP_ID/'${NEXT_PUBLIC_FIREBASE_APP_ID}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID/'${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'/g" /app/public/env.js
sed -i "s/process.env.NEXT_PUBLIC_API_URL/'${NEXT_PUBLIC_API_URL}'/g" /app/public/env.js

echo "✅ Environment variables setup complete"
echo "📄 Generated .env.local and public/env.js"

# Debug output
echo "🔍 Environment Variables Debug:"
echo "API Key: ${NEXT_PUBLIC_FIREBASE_API_KEY:0:10}..."
echo "Auth Domain: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
echo "Project ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
echo "API URL: ${NEXT_PUBLIC_API_URL}"

# Start the application
exec "$@"